version: '3'
services:

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
    volumes:
    - ./server:/app # This should be removed when running in production

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - server
    volumes:
    - ./client:/app # This should be removed when running in production
